version: '2.2'

services:
       
  myapp-mysql:
    container_name: mysql:5.6
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=rout
      - MYSQL_DATABASE=timesheet
    ports:
      - 3307:3306

  timesheet:
    container_name: timesheet-container
    image: $registry:$BUILD_NUMBER    
    build: ./
    restart: on-failure
    depends_on:
      - myapp-mysql
    ports:
      - 8083:8083
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://myapp-mysql:3306/timesheet?autoReconnect=true&useSSL=false